### ISSUE TITLE
requirement package  and dataset

### ISSUE THREAD

**Issue by woshituobaye** [mathilde-b/CDA#2]
![image](https://user-images.githubusercontent.com/20101085/63749164-718e7580-c8dd-11e9-8959-262e0ea56f83.png)

can not found package : MySampler 
and  dataset:  ivdm3seg

**Comment by CDAMICCAI2019** [comment]
Hello, so the MySampler file was added. for the dataset, you need to download it at https://ivdm3seg.weebly.com/data.html. We used the Water (Wat) modality as the Source domain, and the In-Phase (IP) modality as the Target domain. Note: in our experiments we rotated the data from the sagittal plane to the transverse plane.

Download the data and put in the data/sagittal folder, then rotate and save into the data/transverse folder, both for the Wat and the IP modality:

python rotate.py  --base_folder='./data/transverse/IP/' --folders=['train','val'] --save_folder='./data/sagittal/IP/' --rot=’rot’  --grp_regex="Subj_\\d+_"

let me know if this makes it work !

**Comment by woshituobaye** [comment]
hello!  The dataset can not download now.

**Comment by woshituobaye** [comment]
Could you recommend some data sets?

**Comment by CDAMICCAI2019** [comment]
Hello, so I really do think the dataset is still available, you have to sign the form as explained at the bottom of the page. It will take a week or two for you to receive it. In the meantime you can play with a toy dataset, or another cross-modality dataset. You can look up in past miccai challenges for example ! In this paper https://arxiv.org/pdf/1812.07907.pdf they used another cross modality dataset, but it is a much more challenging one so I wouldn't recommend it as a start.

**Comment by woshituobaye** [comment]
the dataset still can not download now.  anyway thank your recommend ! hh

**Comment by ITEliteCCY** [comment]
> hello! The dataset can not download now.

Did you get the data set?Could you please send me a copy to email: 925562020@qq.com, thank you very much.

**Comment by ITEliteCCY** [comment]
> Hello, so I really do think the dataset is still available, you have to sign the form as explained at the bottom of the page. It will take a week or two for you to receive it. In the meantime you can play with a toy dataset, or another cross-modality dataset. You can look up in past miccai challenges for example ! In this paper https://arxiv.org/pdf/1812.07907.pdf they used another cross modality dataset, but it is a much more challenging one so I wouldn't recommend it as a start.

I signed the form as explained at the bottom of the page and sent an email to guoyan.zheng@istb.unibe.ch, but the email failed and was returned.

**Comment by zs963048949** [comment]
> > Hello, so I really do think the dataset is still available, you have to sign the form as explained at the bottom of the page. It will take a week or two for you to receive it. In the meantime you can play with a toy dataset, or another cross-modality dataset. You can look up in past miccai challenges for example ! In this paper https://arxiv.org/pdf/1812.07907.pdf they used another cross modality dataset, but it is a much more challenging one so I wouldn't recommend it as a start.
> 
> I signed the form as explained at the bottom of the page and sent an email to [guoyan.zheng@istb.unibe.ch](mailto:guoyan.zheng@istb.unibe.ch), but the email failed and was returned.

Yes,I also had the same problem.Have you solved it？

**Comment by zs963048949** [comment]
> Hello, so I really do think the dataset is still available, you have to sign the form as explained at the bottom of the page. It will take a week or two for you to receive it. In the meantime you can play with a toy dataset, or another cross-modality dataset. You can look up in past miccai challenges for example ! In this paper https://arxiv.org/pdf/1812.07907.pdf they used another cross modality dataset, but it is a much more challenging one so I wouldn't recommend it as a start.
Hi,Did you have this code of the paper(https://arxiv.org/pdf/1812.07907.pdf) and dataset? Where can I get it? Thanks.

**Comment by hichchou** [comment]
Hi, the contact mail provided to access the dataset doesn't exist anymore. Is there any other way to access the dataset ?

**Comment by mathilde-b** [comment]
Hello, unfortunalely no, i don't know of another way to access the data. In the newest version of the CDA, we use 2 new datasets, a prostate and a heart one. Please see : https://github.com/mathilde-b/SFDA
These datasets are newer so better maintained. They are publicly accessible.
