### ISSUE TITLE
How do I get dataset

### ISSUE THREAD

**Issue by ITEliteCCY** [mathilde-b/CDA#3]
Did you get the data set?Could you please send me a copy to email: 925562020@qq.com, thank you very much.

**Comment by mathilde-b** [comment]
Hello, the access to the dataset is through the MICCAI challenge website : https://ivdm3seg.weebly.com/

**Comment by mathilde-b** [comment]
In the newest version of the CDA, we use 2 new datasets, a prostate and a heart one. Please see : https://github.com/mathilde-b/SFDA
These datasets are newer so better maintained. They are publicly accessible.
