### ISSUE TITLE
AttributeError:'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ITEliteCCY** [mathilde-b/CDA#4]
I didn't run the rotate. py, but put pictures directly into the transverse folder.Then run main.py with the following error:
![image](https://user-images.githubusercontent.com/56783529/70405276-974c1e80-1a77-11ea-98b1-41059530e995.png)

**Comment by mathilde-b** [comment]
Hello, this error comes from the regular expression of your files. Can you give me a screenshot of the lists of files in your directory Wat/GT for example ? The regular expression should match something like Subj_\\d+_\\d+.png for example : Subj_0_1.png
You could try the newest version of the project.
Thanks
