### ISSUE TITLE
Reading nii files

### ISSUE THREAD

**Issue by ok-sweat** [mathilde-b/CDA#9]
I found in rotate.py and dataloader.py, both of them read ".png", but the original image in dataset is ".nii". Data can't be loaded because the mismatch.

And I also found in rotate.py, given command : 
`python rotate.py  --base_folder='./data/transverse/IP/' --folders=['train','val'] --save_folder='./data/sagittal/IP/' --rot=’rot’  --grp_regex="Subj_\\d+_"
`
Based on your description, put original data in './data/sagittal' and rotate.py will convert it to './data/transverse', but in the command, data will be read from './data/transverse/IP/' and save into './data/sagittal/IP/'. Is it a mistake or my misunderstanding?

I am interested in your work and trying to repeat it, so I am wondering how to implement this code.

**Comment by mathilde-b** [comment]
Hello, I transformed the data to png ! should be easy, just read the data and rewrite it. Its actually not necessary, can't remember why I did this :) 
yes, it should be :
python rotate.py --base_folder='./data/transverse/IP/' --folders=['train','val'] --save_folder='./data/transverse/IP/' --rot=’rot’ --grp_regex="Subj_\\d+_"

**Comment by CDAMICCAI2019** [comment]
Hello, now the code reads nii files.  I will put the code for rotating the slices. thank you !
